#![cfg(feature = "vectors")]
//! SAS golden vector tests.
//!
//! Loads sas.vectors.json (generated by TS SDK) and verifies that the
//! Rust `compute_sas` produces identical output for each test case.

#![allow(non_snake_case)]

use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct SasVectors {
    version: u32,
    cases: Vec<SasCase>,
}

#[derive(Deserialize)]
struct SasCase {
    name: String,
    identity_a_hex: String,
    identity_b_hex: String,
    ephemeral_a_hex: String,
    ephemeral_b_hex: String,
    expected_sas: String,
}

fn vectors_dir() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .join("..")
        .join("..")
        .join("ts")
        .join("bolt-core")
        .join("__tests__")
        .join("vectors")
}

fn hex_to_32(hex: &str) -> [u8; 32] {
    let bytes = bolt_core::encoding::from_hex(hex).expect("invalid hex");
    bytes.try_into().expect("expected 32 bytes")
}

#[test]
fn sas_golden_vectors_from_file() {
    let path = vectors_dir().join("sas.vectors.json");
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
    let vecs: SasVectors = serde_json::from_str(&data).expect("sas vectors failed to parse");

    assert_eq!(vecs.version, 1);
    assert!(
        vecs.cases.len() >= 3,
        "expected at least 3 SAS vector cases, got {}",
        vecs.cases.len()
    );

    for case in &vecs.cases {
        let id_a = hex_to_32(&case.identity_a_hex);
        let id_b = hex_to_32(&case.identity_b_hex);
        let eph_a = hex_to_32(&case.ephemeral_a_hex);
        let eph_b = hex_to_32(&case.ephemeral_b_hex);

        let sas = bolt_core::sas::compute_sas(&id_a, &id_b, &eph_a, &eph_b);
        assert_eq!(
            sas, case.expected_sas,
            "SAS mismatch for case '{}': got '{}', expected '{}'",
            case.name, sas, case.expected_sas
        );

        // Verify symmetry: swapping A/B produces the same SAS
        let sas_rev = bolt_core::sas::compute_sas(&id_b, &id_a, &eph_b, &eph_a);
        assert_eq!(
            sas_rev, case.expected_sas,
            "SAS symmetry failed for case '{}': reversed got '{}', expected '{}'",
            case.name, sas_rev, case.expected_sas
        );
    }
}

#[test]
fn sas_vector_file_exists_and_not_empty() {
    let path = vectors_dir().join("sas.vectors.json");
    let meta = std::fs::metadata(&path).unwrap_or_else(|e| panic!("{}: {}", path.display(), e));
    assert!(
        meta.len() > 200,
        "sas vectors suspiciously small ({} bytes)",
        meta.len()
    );
}
